sudo: required
services:
  - docker

before_install:
  - docker build -t Talha0305/docker-react -f Dockerfile.dev .

script:
  - docker run Talha0305/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "React App"
  env: "ReactApp-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-966139103938"
  bucket_path: "React App"
  on:
    branch: master
  access_key_id : $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"